### ISSUE TITLE
可以添加对象存储功能~

### ISSUE THREAD

**Issue by casuallyone** [nineaiyu/xadmin-server#81]
项目默认是存本地，正式服务时使用可能使用NGINX直接访问，提供OSS存储方案
安装存储第三方库（如果直接使用阿里云、AWS不需要安装MINIO）
```shell
pip install django-storages boto3 minio
```
### 添加配置
``` yml
# config.yml

# Minio服务地址
MINIO_ENDPOINT_URL: "http://127.0.0.1:9000"
# Minio账号或KEY
MINIO_ACCESS_KEY: "USR"
# Minio密码或KEY
MINIO_SECRET_KEY: "PWD"
# Minio中桶名称，需要自己创建
MINIO_BUCKET_NAME: "xadmin"
# 同名文件是否允许覆盖
MINIO_FILE_OVERWRITE: false
# 是否使用Https，False就是使用Http
MINIO_USE_SSL: false
```

### 添加第三方应用并设置存储
```python
# server/settings/base.py
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'system.apps.SystemConfig',  
    'settings.apps.SettingsConfig',
    "notifications.apps.NotificationsConfig",
    'captcha.apps.CaptchaConfig', 
    'message.apps.MessageConfig',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'storages', # 添加的在这里
    'django_celery_results',
    'django_celery_beat',
    'imagekit',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    *XADMIN_APPS,
    'common.apps.CommonConfig'
]

### 静态文件也可一起放在OSS中，不过也可以放在本地
STORAGES = {
    'default': {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            'access_key': CONFIG.MINIO_ACCESS_KEY,
            'secret_key': CONFIG.MINIO_SECRET_KEY,
            'endpoint_url': CONFIG.MINIO_ENDPOINT_URL,
            'bucket_name': CONFIG.MINIO_BUCKET_NAME,
            'file_overwrite': CONFIG.MINIO_FILE_OVERWRITE,
            'use_ssl': CONFIG.MINIO_USE_SSL
        },
    },
    'staticfiles': {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    }
}
```

### 实际使用若需要删除时，删除对应文件，AutoCleanFileMixin好使~

```python
from django.db import models
from common.core.models import AutoCleanFileMixin
# 混用的得放前面，不然会被重写，不生效
class Material(AutoCleanFileMixin,DbAuditModel):
    file = models.FileField(verbose_name="文件", upload_to=upload_directory_path, null=True, blank=True)
```

### 另外针对upload_directory_path做了一点小改进，因为在post请求发送时，对应pk可能还未生成，所以instance.pk可能为None，所以可以直接换成username~
```python
# common/core/models.py
# line 100
def upload_directory_path(instance, filename):
    prefix = filename.split('.')[-1]
    tmp_name = f"{filename}_{time.time()}"
    new_filename = f"{uuid.uuid5(uuid.NAMESPACE_DNS, tmp_name).__str__().replace('-', '')}.{prefix}"
    labels = instance._meta.label_lower.split('.')
    if creator:=getattr(instance,"creator",None):
        creator_name = creator.username
    else:
        creator_name = "Anonymous"

    return os.path.join(labels[0], labels[1], creator_name, new_filename)
```
